name: CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          echo "No dependencies yet"

      - name: Run security scan (Bandit)
        run: |
          pip install bandit
          bandit -r .

      - name: Run dependency vulnerability scan (SCA)
        run: |
          pip install pip-audit
          pip-audit --output pip-audit-report.txt || true
          cat pip-audit-report.txt

      - name: Run app
        run: |
          python app.py